site_name: The Roadmap
site_author: Dario Martinez
site_description: >-
  The roadmap, from zero to hero, to become a software engineer.
repo_name: dariomtz/the-roadmap
repo_url: https://github.com/dariomtz/the-roadmap/
site_url: https://example.com/
theme:
  name: material 
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
  palette:
    - scheme: default
      primary: black
      accent: red
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home: index.md
  - Overview: 
    - Getting Started: overview/get_started.md
    - Resume: overview/resume.md
    - Resume Improvements: overview/improve-resume.md
    - Resume Example: overview/resume-example.md
    - Interviews: overview/interviews.md
    - Technical Interviews: overview/tech-interviews.md
    - Interview Preparation: overview/interview-prep.md
    - Start Applying : overview/start-applying.md
  - Data Strucutres:
    - Overview: data-structures/overview.md
    - Arrays: data-structures/arrays.md
    - Hash Tables: data-structures/hash-tables.md
    - Linked Lists: data-structures/linked-lists.md
    - Stacks: data-structures/stacks.md
    - Queues: data-structures/queues.md
    - Trees: data-structures/trees.md
    - Heaps: data-structures/heaps.md
    - Trees Advanced: data-structures/trees-advanced.md
  - Algorithms:
    - Overview: algorithms/overview.md
markdown_extensions: 
  - admonition
  - pymdownx.details
  - pymdownx.superfences
